server:
  port: 80

servlet:
  context-path: /

spring:
  datasource:
    # 换数据源（JDBC连接池）
    type: com.alibaba.druid.pool.DruidDataSource
    # 设置连接信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/friends
    username: root
    password: M202271503