server:
  port: 80
  # 开发阶段浏览器不设置缓存，静态资源更新后立马就能访问到
  tomcat:
    processor-cache: 0


servlet:
  context-path: /



spring:
  datasource:
    # 换数据源（JDBC连接池）
    type: com.alibaba.druid.pool.DruidDataSource
    # 设置连接信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/friends
    username: root
    password: M202271503
  # 开发阶段关闭浏览器缓存
  thymeleaf:
    cache: false
  # 邮箱配置
  mail:
    default-encoding: utf-8
    # 邮箱主机
    host: smtp.qq.com
    # 发送邮件的邮箱的账号密码
    username: 877319363@qq.com
    password: ehypoybrqxbebdjf # 这里设置开启SMTP的激活码
    protocol: smtps # smtps 是加了SSL的smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true # 开启SSL


mybatis:
  # 设置映射文件（mapper.xml）的路径
  mapper-locations: classpath:mapper/*.xml
  # 向pojo对象封装数据的时要扫描的包，这里定义后配置文件中就可以省略包名
  type-aliases-package: site.zhangerfa.pojo
  configuration:
    # 自动完成MySQL中下划线和Java中驼峰命名的转换
    map-underscore-to-camel-case: true
    # 启用属性自增的组件
    use-generated-keys: true

logging:
  level:
    web: error